### ISSUE TITLE
The identity function is not a hash function

### ISSUE THREAD

**Issue by adamnovak** [benedictpaten/sonLib#30]
https://github.com/benedictpaten/sonLib/blob/7e4a8fabb18e3ad35293889298fb2543262e62c3/C/impl/sonLibHash.c#L22-L34

**Comment by joelarmstrong** [comment]
There is additional hashing done on top of this inside the hash library itself--it turns out pretty OK most of the time.

https://github.com/benedictpaten/sonLib/blob/1afbd9719e535b599fab20626a24a63331dc7623/C/impl/hashTableC.c#L69

what do you get if you run stHash_printDiagnostics on a problematic hash table?

**Comment by adamnovak** [comment]
I saw that, but in pinchesAndCacti we were computing the hash of a snarl by
xoring the hashes of two pointers, which ended up just xoring the pointers,
which pretty much always returned the same result because the pointers were
a consistent distance apart. I didn't bother to do the real diagnostics
because it was clearly broken.

I think it makes the most sense to fix it in sonLib, though. If we're going
to have a pointer hashing function we ought to make it hash, if only to
prevent people trying to use it as a primitive from getting confused.

**Comment by joelarmstrong** [comment]
Ah, that makes a whole lot more sense. I was wondering why it only cropped up in this one case.

I agree that it makes sense to fix it in sonLib.
